### ISSUE TITLE
Get Time

### ISSUE THREAD

**Issue by geniodelmale** [geniodelmale/mission-005#2]
Please implement a RESTful call that returns the current time as a text string

**Comment by fvneerden** [comment]
Looking into this.

**Comment by pvandorp** [comment]
>           Looking into this.

Hi @fvneerden, 

What will you call your API Controller? I will use the same name so it will be easier to merge. I suggest something like DateTimeController?

**Comment by fvneerden** [comment]
> > ```
> >       Looking into this.
> > ```
> 
> Hi @fvneerden,
> 
> What will you call your API Controller? I will use the same name so it will be easier to merge. I suggest something like DateTimeController?

YEah Isn't working for me.

**Comment by pvandorp** [comment]
@fvneerden Why not? Can I help you with something?

**Comment by fvneerden** [comment]
Simple Web API is stupidly complex in .net Core. Can you show me an easy way?

**Comment by pvandorp** [comment]
@fvneerden Are you still working on this?

**Comment by fvneerden** [comment]
@pvandorp NO I've had a look but doesn't work locally for me. Stopped debuggin it.
